name: Actualizar Clima Ecowitt

on:
  schedule:
    - cron: '0 * * * *' # Cada hora. Puedes poner '*/30 * * * *' para cada 30 min.
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Fetch Data
        run: |
          mkdir -p data
          # Agregamos unidades: Celsius (1), hPa (3) y mm (12)
          curl -s -X GET "https://api.ecowitt.net/api/v3/device/real_time?application_key=${{ secrets.ECOWITT_APPLICATION_KEY }}&api_key=${{ secrets.ECOWITT_API_KEY }}&mac=${{ secrets.ECOWITT_STATION_MAC }}&temp_unitid=1&pressure_unitid=3&precip_unitid=12&call_back=all" -o data/latest.json
          
          TIMESTAMP=$(date +%Y%m%d_%H%M)
          cp data/latest.json data/weather_$TIMESTAMP.json
          # Llamada a la API v3
          curl -s -X GET "https://api.ecowitt.net/api/v3/device/real_time?application_key=${{ secrets.ECOWITT_APPLICATION_KEY }}&api_key=${{ secrets.ECOWITT_API_KEY }}&mac=${{ secrets.ECOWITT_STATION_MAC }}&call_back=all" -o data/latest.json
          
          # Creamos una copia histórica por si en el futuro quieres hacer gráficos
          cp data/latest.json data/weather_$TIMESTAMP.json

      - name: Push Changes
        run: |
          git config --global user.name "Weather Bot"
          git config --global user.email "actions@github.com"
          git add data/*.json
          git commit -m "Cron: Actualización de datos meteorológicos $(date)" || exit 0
          git push
